### ISSUE TITLE
Building for LÖVE

### ISSUE THREAD

**Issue by rm-code** [Positive07/test#1]
Hey @Positive07,

I am currently using CI for my game which is written in LÖVE. I remembered that you have this repository and looked at your .travis.yml.

For LÖVE I basically only need to build against luajit, right? Should I pick "luajit=2.0"
or "luajit=2.1"?

Best wishes,
Robert

**Comment by pablomayobre** [comment]
Haha! I'm glad this repository served some purpose at all since I was just testing random stuff and some libraries I had lying around. Feel free to grab everything you need and use it, I grabbed this from someone else ([Kikito](https://github.com/kikito/middleclass/blob/master/.travis.yml))

About LÖVE, it can use any version of Lua it is compiled against, always remember that because (rarely) you may find someone that doesn't use the default and your code won't work.

By default LÖVE uses LuaJIT 2.0.4 in desktop and LuaJIT 2.1.1 in Android and iOS (in order to support 64bits ARM devices), LÖVE 0.11.0 will probably use LuaJIT 2.1.1 if that becomes a stable release.

Since Travis doesn't complain about the number of jobs you run with it (as long as your code is Open Source that is) you may as well run against all versions, but running against the two "luajit=" ones is pretty safe (note that if you only need desktop you can use "luajit=2.0" and that will do it)

Cheers,
Pablo

**Comment by rm-code** [comment]
Thanks for the quick reply 😄  I decided to get rid of the `loadstring` and `unpack` functions and am now still building against Lua 5.1, 5.2 and 5.3 as well as LuaJIT.

**Comment by pablomayobre** [comment]
Oh no problem, and I'm glad you did!

Remember that you can do this:

``` lua
local loadstring = loadstring or load
local unpack = unpack or table.unpack
```

**Comment by rm-code** [comment]
Yeah I actually did it like that: https://github.com/rm-code/On-The-Roadside/commit/5e3e2fa07e212c3b15e32ac52acabbf24f048cd4?diff=unified#diff-26a7f597c63b26e95c8f3f5023519edfR17

Strangely the Travis build still fails: "src/SaveHandler.lua:17:20: accessing undefined variable loadstring" ... guess I'll have to add loadstring to the globals for 5.3 or something like that.

**Comment by pablomayobre** [comment]
Try `loadstring = loadstring and loadstring or load` that may fix it

**Comment by rm-code** [comment]
Still failing. I think it's not failing because of the code, but because luacheck sees it as a "undeclared global variable" or something like that.

**Comment by rm-code** [comment]
Ah well ... I'll just build against LuaJIT. If somebody knows how to build a custom LÖVE version they probably also can fix those small code issues 😆

**Comment by pablomayobre** [comment]
Oh! The problem is that you deleted the [`max`](http://luacheck.readthedocs.io/en/stable/cli.html#command-line-options) before the `+busted` which was [here in this line](https://github.com/Positive07/test/blob/master/.travis.yml#L30) but is not [here in this line](https://github.com/rm-code/On-The-Roadside/blob/develop/.travis.yml#L21) of your .travis.yml

**Comment by rm-code** [comment]
That's exactly what I was missing. Thanks a lot for your help! ❤️

**Comment by pablomayobre** [comment]
No problem! I'm glad I could help, it served as a little distraction too 😉
